### ISSUE TITLE
response time

### ISSUE THREAD

**Issue by hamzaaslam0497** [iam-mhaseeb/Python-Implementation-of-LSA#1]
when we use our own data or document rather than your documents the output comes not valid....
for example if i take 5 documents that are 
documents = ["Computer is a machine", "Dog is animal", "Hamza is human", "I am in Multan" , "How are you"]
and match "dog is animal"
then  the output comes
[(0,1.0), (1,1.0),(2,1.0),(3,0.0),(4,0.0)]
which is invalid
and if i implement that code on text files than it take a large amount of time to execute
for example
if i read files from my pc using glob and stores the file in documents[] then your program take very large time to execute more than 1 hour

**Comment by iam-mhaseeb** [comment]
Your output `[(0,1.0), (1,1.0),(2,1.0),(3,0.0),(4,0.0)]` shows your input has most similarity with document 0 and then 1 ,2 with 100% similarity that is expected as our model learns on semantic similarity instead of syntactical similarity. Model is not able to learn each document properly and their features are mixing up. Use large dataset with lemmatization and stemming for better results. 
It taking too long because your dataset might be large in size.

**Comment by hamzaaslam0497** [comment]
yes our data set is very large i want to implement that code on a book to search a query so you have any solution that reduce the execution time

**Comment by iam-mhaseeb** [comment]
To speed up process use smaller dataset.
